#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pygobject
Version  : 3.42.2
Release  : 79
URL      : https://download.gnome.org/sources/pygobject/3.42/pygobject-3.42.2.tar.xz
Source0  : https://download.gnome.org/sources/pygobject/3.42/pygobject-3.42.2.tar.xz
Summary  : Python bindings for GObject Introspection
Group    : Development/Tools
License  : CC-BY-SA-3.0 LGPL-2.1
Requires: pygobject-license = %{version}-%{release}
Requires: pygobject-python = %{version}-%{release}
Requires: pygobject-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : pkgconfig(py3cairo)
BuildRequires : pypi(pycairo)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)

%description
.. image:: https://pygobject.readthedocs.io/en/latest/_images/pygobject.svg
:align: center
:width: 400px
:height: 98px

%package dev
Summary: dev components for the pygobject package.
Group: Development
Provides: pygobject-devel = %{version}-%{release}
Requires: pygobject = %{version}-%{release}

%description dev
dev components for the pygobject package.


%package extras
Summary: extras components for the pygobject package.
Group: Default

%description extras
extras components for the pygobject package.


%package license
Summary: license components for the pygobject package.
Group: Default

%description license
license components for the pygobject package.


%package python
Summary: python components for the pygobject package.
Group: Default
Requires: pygobject-python3 = %{version}-%{release}

%description python
python components for the pygobject package.


%package python3
Summary: python3 components for the pygobject package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pygobject package.


%prep
%setup -q -n pygobject-3.42.2
cd %{_builddir}/pygobject-3.42.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1666717717
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dtests=false  builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs

%install
mkdir -p %{buildroot}/usr/share/package-licenses/pygobject
cp %{_builddir}/pygobject-%{version}/COPYING %{buildroot}/usr/share/package-licenses/pygobject/597bf5f9c0904bd6c48ac3a3527685818d11246d || :
cp %{_builddir}/pygobject-%{version}/docs/images/LICENSE %{buildroot}/usr/share/package-licenses/pygobject/37e8ad1b8f297bce2b0974196aa6998cc7f8e418 || :
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/pygobject-3.0/pygobject.h
/usr/lib64/pkgconfig/pygobject-3.0.pc

%files extras
%defattr(-,root,root,-)
/usr/lib/python3.11/site-packages/gi/_gi_cairo.cpython-311-x86_64-linux-gnu.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pygobject/37e8ad1b8f297bce2b0974196aa6998cc7f8e418
/usr/share/package-licenses/pygobject/597bf5f9c0904bd6c48ac3a3527685818d11246d

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3.11/site-packages/PyGObject-3.42.2.egg-info
/usr/lib/python3.11/site-packages/gi/__init__.py
/usr/lib/python3.11/site-packages/gi/__pycache__/__init__.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/__pycache__/_constants.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/__pycache__/_error.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/__pycache__/_gtktemplate.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/__pycache__/_option.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/__pycache__/_ossighelper.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/__pycache__/_propertyhelper.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/__pycache__/_signalhelper.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/__pycache__/docstring.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/__pycache__/importer.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/__pycache__/module.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/__pycache__/pygtkcompat.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/__pycache__/types.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/_constants.py
/usr/lib/python3.11/site-packages/gi/_error.py
/usr/lib/python3.11/site-packages/gi/_gi.cpython-311-x86_64-linux-gnu.so
/usr/lib/python3.11/site-packages/gi/_gtktemplate.py
/usr/lib/python3.11/site-packages/gi/_option.py
/usr/lib/python3.11/site-packages/gi/_ossighelper.py
/usr/lib/python3.11/site-packages/gi/_propertyhelper.py
/usr/lib/python3.11/site-packages/gi/_signalhelper.py
/usr/lib/python3.11/site-packages/gi/docstring.py
/usr/lib/python3.11/site-packages/gi/importer.py
/usr/lib/python3.11/site-packages/gi/module.py
/usr/lib/python3.11/site-packages/gi/overrides/GIMarshallingTests.py
/usr/lib/python3.11/site-packages/gi/overrides/GLib.py
/usr/lib/python3.11/site-packages/gi/overrides/GObject.py
/usr/lib/python3.11/site-packages/gi/overrides/Gdk.py
/usr/lib/python3.11/site-packages/gi/overrides/GdkPixbuf.py
/usr/lib/python3.11/site-packages/gi/overrides/Gio.py
/usr/lib/python3.11/site-packages/gi/overrides/Gtk.py
/usr/lib/python3.11/site-packages/gi/overrides/Pango.py
/usr/lib/python3.11/site-packages/gi/overrides/__init__.py
/usr/lib/python3.11/site-packages/gi/overrides/__pycache__/GIMarshallingTests.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/overrides/__pycache__/GLib.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/overrides/__pycache__/GObject.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/overrides/__pycache__/Gdk.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/overrides/__pycache__/GdkPixbuf.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/overrides/__pycache__/Gio.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/overrides/__pycache__/Gtk.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/overrides/__pycache__/Pango.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/overrides/__pycache__/__init__.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/overrides/__pycache__/keysyms.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/overrides/keysyms.py
/usr/lib/python3.11/site-packages/gi/pygtkcompat.py
/usr/lib/python3.11/site-packages/gi/repository/__init__.py
/usr/lib/python3.11/site-packages/gi/repository/__pycache__/__init__.cpython-311.pyc
/usr/lib/python3.11/site-packages/gi/types.py
/usr/lib/python3.11/site-packages/pygtkcompat/__init__.py
/usr/lib/python3.11/site-packages/pygtkcompat/__pycache__/__init__.cpython-311.pyc
/usr/lib/python3.11/site-packages/pygtkcompat/__pycache__/generictreemodel.cpython-311.pyc
/usr/lib/python3.11/site-packages/pygtkcompat/__pycache__/pygtkcompat.cpython-311.pyc
/usr/lib/python3.11/site-packages/pygtkcompat/generictreemodel.py
/usr/lib/python3.11/site-packages/pygtkcompat/pygtkcompat.py
